# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

release:
  prerelease: auto

before:
  hooks:
    - go mod download

builds:
  - id: gctx
    main: ./cmd/gctx
    binary: gctx
    ldflags:
      - -s -w
      - -X=main.version={{.Tag}}
      - -X=main.commit={{.ShortCommit}}
      - -X=main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - id: gctx-archive
    ids:
      - gctx
    name_template: >-
      gctx_{{ .Tag }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
