[tools]
go = "latest"

[tasks.build]
description = "Build the CLI"
run = "goreleaser build --snapshot --clean --single-target"

[tasks.test]
description = "Run all unit tests"
run = "go test ./..."

[tasks.lint]
description = "Format all Go source files"
run = "gofmt -w -s ."

[tasks.run]
description = "Run the CLI"
usage = '''
arg "<subcommand>" help="gctx subcommand" {
  choices "init" "version" "config" "completion"
}
'''
run = "go run cmd/gctx/main.go gctx"
